//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace OrderApi
{

    public partial class OrderDB : LinqToDB.Data.DataConnection
    {
        /// <summary>
        /// µÍ∆Ã±Ì
        /// </summary>
        public ITable<SHOP> Shops { get { return this.GetTable<SHOP>(); } }
        public ITable<TEST> Tests { get { return this.GetTable<TEST>(); } }

        public OrderDB()
        {
            InitDataContext();
            InitMappingSchema();
        }

        public OrderDB(string configuration)
            : base(configuration)
        {
            InitDataContext();
            InitMappingSchema();
        }

        partial void InitDataContext();
        partial void InitMappingSchema();
    }

    /// <summary>
    /// µÍ∆Ã±Ì
    /// </summary>
    [Table(Schema = "dbo", Name = "SHOP")]
    public partial class SHOP
    {
        [Column(), NotNull] public string ID { get; set; } // nvarchar(50)
        [Column("DATETIME_CREATED"), NotNull] public DateTime DatetimeCreated { get; set; } // datetime
        [Column("USER_CREATED"), NotNull] public string UserCreated { get; set; } // nvarchar(50)
        [Column("SHOP_NAME"), NotNull] public string ShopName { get; set; } // nvarchar(50)
        [Column("SHOP_CODE"), NotNull] public string ShopCode { get; set; } // nvarchar(50)
        [Column("SHOP_DESC"), Nullable] public string ShopDesc { get; set; } // nvarchar(max)
        [Column(), NotNull] public string ADDRESS { get; set; } // nvarchar(max)
        [Column(), Nullable] public decimal? PHONE { get; set; } // decimal(18, 0)
        [Column(), Nullable] public string BOSS { get; set; } // nvarchar(50)
        [Column("IS_EFFECTIVE"), NotNull] public string IsEffective { get; set; } // nvarchar(50)
    }

    [Table(Schema = "dbo", Name = "TEST")]
    public partial class TEST
    {
        [Column, Nullable] public string ID { get; set; } // nchar(10)
        [Column, Nullable] public string WWW { get; set; } // nchar(10)
        [Column, Nullable] public string EEE { get; set; } // nchar(10)
    }
}

#pragma warning restore 1591
